string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16")
if (compile_threaded)
  string(APPEND LDFLAGS " -fopenmp")
endif()
string(APPEND FFLAGS " -fallow-argument-mismatch -fallow-invalid-boz")
set(CMAKE_C_COMPILER "/usr/local/bin/gcc")
set(CMAKE_CXX_COMPILER "/usr/local/bin/g++")
set(CMAKE_Fortran_COMPILER "/usr/local/bin/gfortran")
set(SFC "/usr/local/bin/gfortran")
set(SCC "/usr/local/bin/gcc")
set(SCXX "/usr/local/bin/g++")
set(MPIFC "/usr/local/mpich/bin/mpif90")
set(MPICC "/usr/local/mpich/bin/mpicc")
set(MPICXX "/usr/local/mpich/bin/mpicxx")
set(CXX_LINKER "FORTRAN")
set(SUPPORTS_CXX "TRUE")
set(NETCDF_PATH "/usr/local/netcdf")
set(PNETCDF_PATH "/usr/local/pnetcdf")
string(APPEND SLIBS " $(shell $(NETCDF_PATH)/bin/nf-config --flibs) -framework Accelerate")
string(APPEND SLIBS " -L/usr/local/netcdf/lib -lnetcdff -lnetcdf -lm")
string(APPEND SLIBS " -L/usr/local/lib -llapack -lblas")

# include_directories(/usr/local/mpich/include)

# set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L/usr/lib -ld64")
# set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -L/usr/lib -ld64")
# set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -L/usr/lib -ld64")
# set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} -L/usr/lib -ld64")
